---
# playbook that runs our VPC networking environment

- hosts: vpc
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ aws_region }}"
  tasks:
    - include_tasks: create_vpc.yml
    - include_tasks: create_gateways.yml
    - include_tasks: facts.yml
    - include_tasks: create_load_balancer.yml